### ISSUE TITLE
Error prompt at main screen

### ISSUE THREAD

**Issue by hsvfan1982** [prosthetichead/GarlicPress#104]
Hi there,
1.) I get an error Message at the main screen, when selecting an other game in the list. (Screenschot and error Message are attached)
2.) I've made some Media Layer Collections in the Editor. That works pretty good. Out of the Editor it is possible for me to update the Artwork at my Device. But this is only possible one by one...
If i want to update the Art at the main screen, it begins to update and an counter is counting down the remaining time till 0. After it reaches 0 it begins to count up the remaining time?!? I've benn waiting there since it shows about 30 minutes, but nothing happens with the artwork on my device... Even if i cancel the Updating nothing will happen. I have to hard-close the prog...

My OS is Windows 11

<img width="760" alt="Screenshot 2023-11-04 171124" src="https://github.com/prosthetichead/GarlicPress/assets/149892188/3f2490b4-57cd-4136-be55-2e0085bf52f2">

The Complete Text of the Error Promp is:
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GarlicPress.GameMediaGeneration.DrawGameTexts(Graphics graphics, List`1 games, String selectedGame) in C:\Users\ashle\source\repos\GarlicPress\classes\GameMediaGeneration.cs:line 276
   at GarlicPress.GameMediaGeneration.OverlayImageWithSkinBackground(Bitmap imageToOverlay, GarlicSystem selectedSystem, List`1 games, String selectedGame) in C:\Users\ashle\source\repos\GarlicPress\classes\GameMediaGeneration.cs:line 199
   at GarlicPress.MainForm.UpdateImageFromDevice(FileStatistics item) in C:\Users\ashle\source\repos\GarlicPress\forms\MainForm.cs:line 220
   at GarlicPress.MainForm.fileListBox_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\ashle\source\repos\GarlicPress\forms\MainForm.cs:line 192
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Private.CoreLib.dll.
----------------------------------------
GarlicPress
    Assembly-Version: 0.0.2310.11.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Runtime.dll.
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/System.Configuration.ConfigurationManager.dll.
----------------------------------------
System.ObjectModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.ObjectModel.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51811.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/System.Windows.Forms.dll.
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51811.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/System.Windows.Forms.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Collections.Specialized.dll.
----------------------------------------
System.Threading
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Threading.dll.
----------------------------------------
System.Collections
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Collections.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Private.Uri.dll.
----------------------------------------
System.Diagnostics.Process
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Diagnostics.Process.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Collections.NonGeneric.dll.
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.Memory
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Memory.dll.
----------------------------------------
System.Security.Cryptography
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Security.Cryptography.dll.
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Collections.Concurrent.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.ComponentModel.TypeConverter.dll.
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Xml.ReaderWriter.dll.
----------------------------------------
System.Private.Xml
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Private.Xml.dll.
----------------------------------------
System.Net.WebClient
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Net.WebClient.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Text.Encoding.Extensions.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Threading.Thread.dll.
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Runtime.Serialization.Formatters.dll.
----------------------------------------
System.Xml.XmlSerializer
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Xml.XmlSerializer.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/System.Drawing.Common.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 7.0.1323.51811.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/Accessibility.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/Microsoft.Win32.SystemEvents.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.ComponentModel.dll.
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Numerics.Vectors.dll.
----------------------------------------
System.Runtime.Loader
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Runtime.Loader.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51811.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/de/System.Windows.Forms.resources.dll.
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/System.Resources.Extensions.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51811.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.13/System.Drawing.dll.
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Diagnostics.FileVersionInfo.dll.
----------------------------------------
Octokit
    Assembly-Version: 7.0.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/netstandard.dll.
----------------------------------------
System.Net.Http
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Net.Http.dll.
----------------------------------------
System.Net.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Net.Primitives.dll.
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Diagnostics.Tracing.dll.
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Diagnostics.DiagnosticSource.dll.
----------------------------------------
System.Net.Security
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Net.Security.dll.
----------------------------------------
System.Linq
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Linq.dll.
----------------------------------------
System.Net.Quic
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Net.Quic.dll.
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/Microsoft.Win32.Registry.dll.
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Threading.ThreadPool.dll.
----------------------------------------
System.Net.Sockets
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Net.Sockets.dll.
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Threading.Overlapped.dll.
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Net.NameResolution.dll.
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Security.Principal.Windows.dll.
----------------------------------------
System.Security.Claims
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Security.Claims.dll.
----------------------------------------
System.IO.Compression
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.IO.Compression.dll.
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Text.RegularExpressions.dll.
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Linq.Expressions.dll.
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Reflection.Emit.ILGeneration.dll.
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Reflection.Emit.Lightweight.dll.
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Reflection.Primitives.dll.
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
AdvancedSharpAdbClient
    Assembly-Version: 2.5.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.Json
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Text.Json.dll.
----------------------------------------
System.Text.Encodings.Web
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Text.Encodings.Web.dll.
----------------------------------------
System.Runtime.Intrinsics
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Runtime.Intrinsics.dll.
----------------------------------------
System.Text.Encoding.CodePages
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Text.Encoding.CodePages.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Reflection.Metadata.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Collections.Immutable.dll.
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.AspNetCore.Components.WebView.WindowsForms
    Assembly-Version: 1.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.AspNetCore.Components.Web
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.AspNetCore.Components
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly-Version: 1.0.1370.28.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly-Version: 1.0.1370.28.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/mscorlib.dll.
----------------------------------------
Microsoft.AspNetCore.Components.WebView
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.JSInterop
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Options
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileProviders.Composite
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Tasks
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Threading.Tasks.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Runtime.Extensions.dll.
----------------------------------------
Microsoft.Extensions.FileProviders.Embedded
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.XDocument
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Xml.XDocument.dll.
----------------------------------------
System.Private.Xml.Linq
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Private.Xml.Linq.dll.
----------------------------------------
Markdig
    Assembly-Version: 0.33.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 7.0.0.0.
    Win32-Version: 7.0.1323.51816.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.13/System.Runtime.CompilerServices.Unsafe.dll.
----------------------------------------

************** JIT-Debuggen **************

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]

**RG35xx (please complete the following information):**
 - GarlicOS version: [e.g.  1.4.9]

**Additional context**

**Comment by Illford** [comment]
I’m seeing the same thing when clicking on games or trying to use the mass updater. Whenever it gets to the end of the mass update it leaves everything at “processing” or “retry”. Only if I do the single game upload method does it work, but that’d take forever. I updated from garlicOS 1.4.6 to 1.4.9 and am on windows 10, a intel NUC

**Comment by 00anwi** [comment]
Hello @Illford 
Can you test the new version released yesterday?
There's some changes done to mitigate this error.

**Comment by Illford** [comment]
> Hello @Illford and @hsvfan1982, Can you test the new version released yesterday? There's some changes done to mitigate this error.

It working! It’s fully uploading each to the device. Thank you!
