### ISSUE TITLE
Bug The SSL connection could not be established

### ISSUE THREAD

**Issue by SilverTiger23** [prosthetichead/GarlicPress#49]
**Describe the bug**
When trying to run "Auto Update Art", sometimes an error occurs. If you click continue in the error window, and then click "Auto Update Art" again, then it can be art for the game. But to give an error on the next or after one.

**To Reproduce**
1. Go to 'GarlicPress'
2. Click on 'Auto Update Art'
3. See error "One or more errors occurred (The SSL connection could not be established, see inner exception)"

**Screenshots**

![error](https://github.com/prosthetichead/GarlicPress/assets/141452517/e8a7e270-865c-439c-914a-92d5cd9aef02)
![error2](https://github.com/prosthetichead/GarlicPress/assets/141452517/052d8409-b578-4b0a-a8af-788265568f6f)

**Desktop (please complete the following information):**
 - OS: Win 10 (Russian language)
 - GarlicOS version: 1.4.9

**Additional context**
This is additional information from the error window details.

Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение..
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at GarlicPress.ScreenScraper.GetGameData(String systemId, String romType, String romName, Boolean skipPrompt, String gameid) in C:\Users\ashle\source\repos\GarlicPress\classes\ScreenScraper.cs:line 44
   at GarlicPress.MainForm.UpdateArt(Boolean promptName) in C:\Users\ashle\source\repos\GarlicPress\forms\MainForm.cs:line 461
   at GarlicPress.MainForm.btnUpdateImg_Click(Object sender, EventArgs e) in C:\Users\ashle\source\repos\GarlicPress\forms\MainForm.cs:line 373
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
System.Private.CoreLib
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Private.CoreLib.dll
----------------------------------------
GarlicPress
    Версия сборки: 0.0.2307.301
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.20/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ObjectModel.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.2023.32104
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.20/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.2023.32104
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.20/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Threading.dll
----------------------------------------
System.Collections
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.dll
----------------------------------------
System.Private.Uri
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Diagnostics.Process
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.Process.dll
----------------------------------------
System.Collections.NonGeneric
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Memory
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Memory.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Linq
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Linq.dll
----------------------------------------
System.Xml.ReaderWriter
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.WebClient
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Text.Encoding.Extensions.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.dll
----------------------------------------
System.Threading.Thread
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Threading.Thread.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Xml.XmlSerializer.dll
----------------------------------------
System.Diagnostics.TraceSource
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Drawing.Common
    Версия сборки: 7.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
AdvancedSharpAdbClient
    Версия сборки: 2.5.6.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 6.0.2023.32104
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.20/Accessibility.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Версия сборки: 7.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Collections.Concurrent
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.ComponentModel.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Numerics.Vectors
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.20/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.2023.32104
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.20/System.Drawing.dll
----------------------------------------
Octokit
    Версия сборки: 7.0.1.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
netstandard
    Версия сборки: 2.1.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/netstandard.dll
----------------------------------------
System.Net.Http
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.Sockets
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Principal.Windows
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Security.Claims.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Версия сборки: 7.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Text.Json
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Text.Json.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Text.Encodings.Web
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.Intrinsics.dll
----------------------------------------
System.Net.Requests
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.Requests.dll
----------------------------------------
System.Net.WebHeaderCollection
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Web.HttpUtility
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Web.HttpUtility.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Net.ServicePoint
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.ServicePoint.dll
----------------------------------------
System.Runtime.Loader
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 6.0.2.0
    Версия Win32: 6.0.2023.32104
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.20/ru/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Collections.Immutable.dll
----------------------------------------
System.Net.Quic
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Net.Quic.dll
----------------------------------------
System.IO.Compression
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.IO.Compression.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.2023.32017
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.20/System.Diagnostics.FileVersionInfo.dll
----------------------------------------

************** Оперативная отладка (JIT) **************

**Comment by prosthetichead** [comment]
Can you please try this again with the latest version?

**Comment by SilverTiger23** [comment]
This error disappeared, but another error appeared
"error 10054 An existing connection was forcibly closed by the remote host"
if I click continue the error window closes, but the program freezes and does not respond to anything
![error3](https://github.com/prosthetichead/GarlicPress/assets/141452517/683876ba-2029-4104-9a06-853d7802fde1)
![error4](https://github.com/prosthetichead/GarlicPress/assets/141452517/4e6b097e-8ce1-4423-be5e-dc7ca22cbe9b)

**Comment by prosthetichead** [comment]
This is really odd, do you have any other internet or network issues? 
Its like screen scraper are disconnecting you or its blocked? 
are you able to goto screenscraper.fr and use the site without issues?

**Comment by SilverTiger23** [comment]
The network is working stably.
The Scraper program (with www.skraper.net ) also works fine. I used it to download covers before. 
and the screenscraper.fr also opens normally.  I don't even know what the problem is.

**Comment by prosthetichead** [comment]
could something like windows defender or an antivirus or firewall be blocking the app from network access?
